# Generated by Django 3.2.5 on 2021-08-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210804_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='today_special',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
