# Generated by Django 3.2.5 on 2021-08-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_today_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='today_special',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
