# Generated by Django 3.2.5 on 2021-08-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210810_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='comment',
        ),
    ]
