# Generated by Django 3.2.5 on 2021-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_description_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_money_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
