# Generated by Django 3.2.5 on 2021-08-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
