# Generated by Django 3.2.5 on 2021-08-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_order_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='coin',
            new_name='coin_spent',
        ),
    ]
