# Generated by Django 3.2.5 on 2021-08-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_coin_customer_coin_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
