# Generated by Django 3.2.5 on 2021-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210818_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
